# Generated by Django 5.0.6 on 2024-06-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_token_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='token_sent_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
    ]
