# Generated by Django 5.0.6 on 2024-06-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_token_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
