# Generated by Django 5.0.6 on 2024-06-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='token_sent_at',
        ),
    ]
