# Generated by Django 5.0.6 on 2024-06-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customuser_token_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
    ]
