# Generated by Django 5.0.6 on 2024-06-05 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_expiry_time',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
