# Generated by Django 5.0.6 on 2024-06-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_token_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token_expiry_time',
            field=models.DateTimeField(),
        ),
    ]
